overwrite: true
hooks:
  afterAllFileWrite:
    - yarn prettier --write
    - yarn eslint --ext ts --fix
generates:
  schema.graphql:
    schema:
      - ${CODELAB_HASURA_GRAPHQL_ENDPOINT}/v1/graphql:
          headers:
            - 'x-hasura-admin-secret': '${HASURA_GRAPHQL_ADMIN_SECRET}'
    plugins:
      - schema-ast

  # Typescript + Apollo
  libs/hasura/src/graphql-client-hasura.generated.ts:
    schema:
      - ${CODELAB_HASURA_GRAPHQL_ENDPOINT}/v1/graphql:
          headers:
            - 'x-hasura-admin-secret': '${HASURA_GRAPHQL_ADMIN_SECRET}'
    documents:
      - libs/modules/**/*.graphql
      - apps/web/**/*.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-document-nodes
    config:
      documentVariableSuffix: 'Gql'
      gqlImport: '@apollo/client#gql'
