# Service
#
# A Service enables network access to a set of Pods in Kubernetes.
#
# Services select Pods based on their labels. When a network request is made to the service, it selects all Pods in the cluster matching the service's selector, chooses one of them, and forwards the network request to it.

apiVersion: v1
kind: Service
metadata:
  name: codelab-service
  namespace: codelab
  labels:
    app: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: web
