branch-defaults:
  cicd/staging:
    environment: app-staging
  master:
    environment: app-staging
environment-defaults:
  app-staging:
    branch: null
    repository: null
global:
  application_name: app
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
