description: 'Build Repo'
steps:
  - restore_cache:
      name: 'Restore NX Cache'
      keys:
        - nx-cache-{{ checksum "node_modules/.cache/nx/lockfile.hash" }}
        - nx-cache
  # Can't use `yarn cli` doesn't exist yet
  - run: npx nx run-many --target=build --projects=platform,cli,landing,websites --parallel=4 --verbose -c ci --nx-bail
  - save_cache:
      name: 'Save Cache'
      key: nx-cache-{{ checksum "node_modules/.cache/nx/lockfile.hash" }}
      paths:
        - ~/project/dist/apps/platform/.next/cache
        - ~/project/dist/apps/landing/.next/cache
        - ~/project/dist/apps/websites/.next/cache
        - ~/project/node_modules/.cache/nx
