description: 'Init Repo'
steps:
  - checkout
  - attach_workspace:
      at: ..
  - restore_cache:
      name: 'Restore Cache'
      keys:
        # We store this only in setup-workspace
        # - yarn-cache-{{ checksum "yarn.lock" }}
        - npm-cache-{{ checksum "yarn.lock" }}
        - nvm-cache-{{ checksum ".nvmrc" }}
        - nx-cache-{{ checksum "node_modules/.cache/nx/lockfile.hash" }}
  # - install-nvm
  - run:
      name: 'Setup Env'
      command: source ~/project/.circleci/config/env.sh
  - run: env
  - nx/set-shas:
      main-branch-name: master
