steps:
  # - restore_cache:
  #     name: 'Restore NVM Cache'
  #     keys:
  #       - nvm-cache-{{ checksum ".nvmrc" }}
  - run:
      command: |
        # Set path before install, otherwise paths will be different in the executors
        echo 'export NODE_OPTIONS=$NODE_OPTIONS' >> $BASH_ENV
        source $BASH_ENV

        echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
        echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV

        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

        #if [ ! -d "$NVM_DIR" ]; then
        #  wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        #fi
      name: Install NVM
  - save_cache:
      key: nvm-cache-{{ checksum ".nvmrc" }}
      name: Save NVM Cache
      paths:
        - ~/.nvm
  - run:
      name: 'Set Node Version'
      command: |
        nvm install 18.16.0
        nvm alias default 18.16.0
        node -v
