# Parallel Slack notification https://github.com/CircleCI-Public/slack-orb/issues/305
# https://support.circleci.com/hc/en-us/articles/360047082992-Send-slack-notification-at-end-of-workflow

#slack-fail-post-step: &slack-fail-post-step
#  post-steps:
#    #    - swissknife/wait_for_job:
#    #        job-name: install-and-build-workspace,lint,unit,e2e,codegen
#    - slack/notify:
#        event: fail
#        channel: $SLACK_CHANNEL_UPDATE
#        template: basic_fail_1

filters-pr: &filters-pr
  filters:
    branches:
      ignore:
        - master

filters-master: &filters-master
  filters:
    branches:
      only:
        - master

resource-class: &resource-class
  parameters:
    size:
      type: string
      default: small

# Each job select which custom executor to use
executor-params: &executor-params
  parameters:
    e:
      type: executor
      default: machine-ubuntu
    size:
      type: string
      default: small
  executor: << parameters.e >>
  resource_class: << parameters.size >>

executor-config: &executor-config
  environment:
    # Application
    NEO4J_URI: bolt://127.0.0.1:7687
    NEO4J_USER: neo4j
    NEO4J_PASSWORD: password
    # CircleCI
    GITHUB_ANTON_M: antonmihaylov
    SLACK_ANTON_M: <@U01HWRY2USE>
    GITHUB_WEBBER: webberwang
    SLACK_WEBBER: <@U0J401GAH>
    GITHUB_ASSIM: assimhabeek
    SLACK_ASSIM: <@U02GJN72TKR>
    GITHUB_NGHIA: phmngocnghia
    SLACK_NGHIA: <@U02DX6U7YGP>
    GITHUB_YASEEN: mohasarc
    SLACK_YASEEN: <@U03B5N7J2N9>
    GITHUB_HAU: hauleIT
    SLACK_HAU: <U040GU0PQ81>
    GITHUB_ELHAM: melhamin
    SLACK_ELHAM: <U0406P3J9T6>
    SLACK_CHANNEL_UPDATE: CQVPNKS8K
    COLOR_SUCCESS: '#b7eb8f'
    COLOR_FAILURE: '#ffccc7'
    NODE_OPTIONS: --max_old_space_size=8192
    #    NODE_ENV: production
    CIRCLE_BASE_REVISION: << pipeline.git.base_revision >>
  working_directory: ~/project

version: 2.1

orbs:
  slack: circleci/slack@4.10.1
  node: circleci/node@4.7.0
  nx: nrwl/nx@1.6.1
  queue: eddiewebb/queue@1.7.0
  swissknife: roopakv/swissknife@0.69.0
  terraform: circleci/terraform@3.1.0

executors:
  # https://github.com/CircleCI-Public/terraform-orb/issues/48#issuecomment-952318485
  # Terraform orb install has issues, so we use our own image
  terraform:
    <<: *resource-class
    environment:
      TF_WORKSPACE: prod
    docker:
      - image: hashicorp/terraform:1.3.1
  machine-ubuntu:
    <<:
      - *executor-config
      - *resource-class
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:2022.04.1
  docker-node:
    <<:
      - *executor-config
      - *resource-class
    docker:
      - image: cimg/node:16.15.1-browsers
  docker-node-neo4j:
    <<:
      - *executor-config
      - *resource-class
    # Docker containers work on a merged networking stack, the second container should make it available in localhost
    # https://discuss.circleci.com/t/whats-the-docker-hostname-for-the-second-container/20101
    docker:
      - image: cimg/node:16.15.1-browsers
      # https://circleci.com/docs/using-docker#using-multiple-docker-images
      # The `command` key is the command issued to the image
      - image: neo4j:5.4.0
        environment:
          NEO4J_AUTH: neo4j/password
          NEO4J_PLUGINS: '["apoc"]'
        command: ['neo4j', 'start']

commands:
  setup-workspace:
    description: 'Setup Workspace'
    steps:
      - checkout
      - attach_workspace:
          at: ..
      - run:
          name: 'Install NVM'
          command: |
            # Set path before install, otherwise paths will be different in the executors
            echo 'export NODE_OPTIONS=$NODE_OPTIONS' >> $BASH_ENV
            source $BASH_ENV

            echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
            echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV

            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - run:
          # Manually install because we can't add `yarn` to terraform orb
          # https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
          name: 'Install Terraform'
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DA418C88A3219F7B
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt update
            sudo apt install terraform
      - run:
          name: 'Set Node Version'
          command: |
            nvm install 16.16.0
            nvm alias default 16.16.0
            node -v
      - run:
          name: 'Setup Env'
          command: |
            # git settings
            echo 'export GIT_COMMIT_MSG=$(git log --format="format:%s" -n 1 ${CIRCLE_SHA1})' >> $BASH_ENV

            # slack settings
            if [ $CIRCLE_USERNAME == $GITHUB_ANTON_M ]; then
              echo 'export SLACK_PARAM_MENTIONS=${SLACK_ANTOM_M}' >> $BASH_ENV

            elif [ $CIRCLE_USERNAME == $GITHUB_ASSIM ]; then
              echo 'export SLACK_PARAM_MENTIONS=${SLACK_ASSIM}' >> $BASH_ENV

            elif [ $CIRCLE_USERNAME == $GITHUB_NGHIA ]; then
              echo 'export SLACK_PARAM_MENTIONS=${SLACK_NGHIA}' >> $BASH_ENV

            elif [ $CIRCLE_USERNAME == $GITHUB_YASEEN ]; then
              echo 'export SLACK_PARAM_MENTIONS=${SLACK_YASEEN}' >> $BASH_ENV

            else
              echo 'export SLACK_PARAM_MENTIONS=${SLACK_WEBBER}' >> $BASH_ENV
            fi

            # finally import bash env
            source $BASH_ENV
      - nx/set-shas:
          main-branch-name: master

  install-package:
    steps:
      - restore_cache:
          name: 'Restore Cache'
          keys:
            - dep-cache-bust-{{ checksum "yarn.lock" }}
          # https://discuss.circleci.com/t/circle-2-0-caching-is-too-limited-to-be-very-useful/11694
      - run:
          name: 'Install NPM Packages'
          command: yarn install --immutable

jobs:
  install-and-build-workspace:
    <<: *executor-params
    steps:
      - setup-workspace
      - install-package
      - run:
          name: 'Clear Cache'
          # clear cache here because NX cache can get quite large, we rely on remote cache instead
          command: |
            rm -rf ~/project/node_modules/nx/.cache
      #            npx cypress cache clear
      #            npx jest --clearCache
      - run:
          name: 'Build CI'
          # Can't use `yarn cli` doesn't exist yet
          command: npx nx run-many --target=build --projects=platform,cli,landing,websites --parallel=4 --verbose -c ci
      - save_cache:
          name: 'Save Cache'
          key: dep-cache-bust-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn
            - ~/.cache
            - ~/project/dist/apps/platform/.next/cache
            - ~/project/dist/apps/landing/.next/cache
            - ~/project/dist/apps/websites/.next/cache
            - ~/project/node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - project/node_modules
            - project/dist

  install-and-build-cli:
    <<: *executor-params
    steps:
      - setup-workspace
      - install-package
      - run:
          name: 'Clear Cache'
          command: |
            rm -rf ~/project/node_modules/nx/.cache
      - run:
          name: 'Build CI'
          command: npx nx build cli --verbose -c ci
      - save_cache:
          name: 'Save Cache'
          key: dep-cache-bust-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn
            - ~/project/node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - project/node_modules
            - project/dist

  lint:
    <<: *executor-params
    environment:
      CIRCLE_BASE_REVISION: << pipeline.git.base_revision >>
      CIRCLE_REVISION: << pipeline.git.revision >>
    steps:
      - setup-workspace
      - run:
          name: 'Run Lint on Repository'
          command: yarn cli tasks lint --stage ci
      - run:
          name: 'Commitlint'
          command: yarn cli tasks commitlint --stage ci

  codegen:
    <<: *executor-params
    steps:
      - setup-workspace
      - run:
          name: 'GraphQL Codegen'
          command: yarn cli tasks codegen --stage ci

  unit:
    <<: *executor-params
    steps:
      - setup-workspace
      - run:
          name: 'Run Unit Tests'
          command: yarn cli tasks unit --stage ci
      # Upload test results
      - store_test_results:
          path: /tmp/test-reports

  integration:
    <<: *executor-params
    steps:
      - setup-workspace
      - run:
          name: 'Run Integration Tests'
          command: yarn cli tasks int --stage ci
          # seed-data.i.spec.ts is running multiple seed/import/export commands which take more than default 10m timeout
          no_output_timeout: 20m

  e2e:
    <<: *executor-params
    # Cypress requires record for parallel to work according to https://github.com/cypress-io/cypress/issues/2520
    parallelism: 4
    steps:
      - setup-workspace
      - setup_remote_docker:
          version: 20.10.14
      - run: npx cypress install
      - run: npx cypress verify
      - run:
          name: 'Run E2E Tests'
          command: yarn cli tasks e2e --stage ci
      - store_artifacts:
          path: ~/project/apps/platform-e2e/src/videos
          destination: cypress/videos
      - store_artifacts:
          path: ~/project/apps/platform-e2e/src/screenshots
          destination: cypress/screenshots
      - store_artifacts:
          path: ~/project/apps/platform-e2e/src/data
          destination: cypress/data

  plan:
    <<: *executor-params
    steps:
      - setup-workspace
      - run:
          name: 'Create .terraformrc file locally'
          command: |
            echo "credentials \"app.terraform.io\" {token = \"$TERRAFORM_TOKEN\"}" >> $HOME/.terraformrc
      - run: terraform --version
      - run:
          name: 'Terraform Format'
          command: terraform -chdir=terraform fmt
      - run:
          name: 'Terraform Init'
          command: yarn cli terraform --stage=prod init
      - run:
          name: 'Terraform Validate'
          command: yarn cli terraform --stage=prod validate
      - run:
          name: 'Terraform Plan'
          command: yarn cli terraform --stage=prod plan
      - persist_to_workspace:
          root: ~/
          paths:
            - .terraformrc
            - project/terraform/.terraform

  apply:
    <<: *executor-params
    steps:
      - setup-workspace
      #      - attach_workspace:
      #          at: ..
      - run:
          name: 'Terraform Apply'
          command: yarn cli terraform --stage=prod apply
  #      - run:
  #          name: 'Terraform Destroy'
  #          command: terraform -chdir=terraform destroy

  notify-success:
    <<: *executor-params
    steps:
      - slack/notify:
          event: pass
          channel: $SLACK_CHANNEL_UPDATE
          # template: basic_success_1
          custom: |
            {
            	"text": "CircleCI job succeeded!",
            	"blocks": [
            		{
            			"type": "header",
            			"text": {
            				"type": "plain_text",
            				"text": "Job Succeeded. :white_check_mark:",
            				"emoji": true
            			}
            		},
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": "*Job*: ${CIRCLE_JOB}"
            				}
            			]
            		},
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": "*Project*:\n $CIRCLE_PROJECT_REPONAME"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Branch*:\n $CIRCLE_BRANCH"
                            },
                            {
            					"type": "mrkdwn",
            					"text": "*Commit*:\n $CIRCLE_SHA1"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Author*:\n $CIRCLE_USERNAME"
            				}
            			],
            			"accessory": {
            				"type": "image",
            				"image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
            				"alt_text": "CircleCI logo"
            			}
            		},
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Mentions*:\n $SLACK_PARAM_MENTIONS"
                    }
                  ]
                },
            		{
            			"type": "actions",
            			"elements": [
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"text": "View Job"
            					},
            					"url": "${CIRCLE_BUILD_URL}"
            				}
            			]
            		}
            	]
            }

  notify-failure:
    <<: *executor-params
    steps:
      - swissknife/wait_for_job:
          job-name: install-and-build-workspace,lint,unit,e2e,codegen
      - slack/notify:
          event: fail
          channel: $SLACK_CHANNEL_UPDATE
          template: basic_fail_1

workflows:
  infra:
    jobs:
      - install-and-build-cli:
          <<: *filters-master
          e: docker-node
          size: medium
      - plan:
          <<: *filters-master
          e: docker-node
          requires:
            - install-and-build-cli
      - hold-apply:
          <<: *filters-master
          type: approval
          requires:
            - plan
      - apply:
          <<: *filters-master
          e: docker-node
          requires:
            - hold-apply

  app-pr:
    jobs:
      # This doesn't actually have access to Slack errors, must be at end of step
      #      - notify-failure:
      #          <<: *filters-pr
      #          e: docker-node
      - install-and-build-workspace:
          <<: *filters-pr
          # Can't build with machine image, causes build issues
          e: docker-node
          size: large
      - lint:
          <<: *filters-pr
          e: docker-node
          size: medium
          requires:
            - install-and-build-workspace
      - codegen:
          <<: *filters-pr
          e: docker-node-neo4j
          requires:
            - install-and-build-workspace
      - unit:
          <<: *filters-pr
          e: docker-node
          # Keeps failing with medium
          size: large
          requires:
            - install-and-build-workspace
      - integration:
          <<: *filters-pr
          e: docker-node-neo4j
          size: medium
          requires:
            - install-and-build-workspace
      - e2e:
          <<: *filters-pr
          e: docker-node-neo4j
          size: xlarge
          requires:
            - install-and-build-workspace
      - notify-success:
          <<: *filters-pr
          e: docker-node
          requires:
            - lint
            - codegen
            - unit
            - integration
            - e2e

  app:
    jobs:
      #      - install-and-build-workspace:
      #          <<: *filters-master
      #          e: docker-node
      #      - lint:
      #          <<: *filters-master
      #          e: docker-node
      #          requires:
      #            - install-and-build-workspace
      #      - unit:
      #          <<: *filters-master
      #          e: docker-node
      #          requires:
      #            - install-and-build-workspace
      - notify-success:
          <<: *filters-master
          e: docker-node
#          requires:
#            - lint
#            - unit
