#
# `--env-file`, a flag for docker-compose, is used for variable substitution
#
# `env_file` is used to find env to inject into docker container at runtime
#
# https://docs.docker.com/compose/environment-variables/
#
version: '3.8'
services:
  neo4j:
    container_name: codelab-neo4j
    image: neo4j:5.4.0
    volumes:
      - codelab-neo4j:/data
      - codelab-neo4j:/plugins
      - codelab-neo4j:/import
      - codelab-neo4j:/logs
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/password
      # - NEO4J_dbms_default__database=neo4j
      # - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      # - NEO4J_dbms_memory_heap_initial__size=512m
      # - NEO4J_dbms_memory_heap_max__size=2G
      # - NEO4J_apoc_uuid_enabled=true
      # - NEO4J_dbms_default__listen__address=0.0.0.0
      # - NEO4J_dbms_allow__upgrade=true
    # networks: ["codelab-neo4j"]
    restart: unless-stopped

  neo4j-test:
    container_name: codelab-neo4j-test
    image: neo4j:5.4.0
    volumes:
      - codelab-neo4j-test:/data
      - codelab-neo4j-test:/plugins
      - codelab-neo4j-test:/import
      - codelab-neo4j-test:/logs
    ports:
      - 7475:7474
      - 7688:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/password
    restart: unless-stopped

volumes:
  codelab-neo4j:
    name: codelab-neo4j-volume
  codelab-neo4j-test:
    name: codelab-neo4j-test-volume
