version: 3
endpoint: https://codelab-ai.hasura.app/
admin_secret: AwuuG9U2VyJHYqSY@ipt!$Uo
# @todo: Hasura env is not working
# @body: According to this https://github.com/hasura/graphql-engine/issues/4129, it should pick up the env when we run `yarn hasura:console`. I've also tried `--envfile=../.env` in case the `--project` makes CWD to `hasura`
# @autoAssign: artonio
#
# admin_secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
api_paths:
  v1_query: v1/query
  v2_query: v2/query
  v1_metadata: v1/metadata
  graphql: v1/graphql
  config: v1alpha1/config
  pg_dump: v1alpha1/pg_dump
  version: v1/version
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
  codegen:
    framework: ''
    output_dir: ''
